### PR TITLE
93 bugs in onoffmodel

### PR DESCRIPTION
**Pull request by FBumann**
Fixed a major bug in OnOffModell regarding consecutive duration constraints.

Further, reorganized the process of creating the constraint.

### CODE REVIEW

**Comment by FBumann** [comment]
Closes #92

**Comment by baumbude** [comment]
I am not so fine with duration_variable:
1. why here suffix "_variable" while on other places you avoid a suffix? just to understand...
2. "duration_in_hours_variable" instead of "duration_variable" would be more easy to understand for user.

P.S.: consecutive_on_hours_min/max earlier where timeseries. Should we really delete this feature?

**Comment by baumbude** [comment]
docstr "constraints added ... " in https://github.com/flixOpt/flixOpt/blob/4b431598434d1e8a09cbeef1934a5b32fdc2a4bd/flixOpt/features.py#L335
ist schön, aber dadurch haben wir schon drei redundante Stellen im Code, die eine Gleichung beschreiben. (2x comment,1x equation)

**Comment by FBumann** [comment]
> docstr "constraints added ... " in https://github.com/flixOpt/flixOpt/blob/4b431598434d1e8a09cbeef1934a5b32fdc2a4bd/flixOpt/features.py#L335
> 
> ist schön, aber dadurch haben wir schon drei redundante Stellen im Code, die eine Gleichung beschreiben. (2x comment,1x equation)

Dann lass das da raus nehmen

**Comment by FBumann** [comment]
Rename duration variable to duration_in_hours

**Pull request merged**
